# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cf64fe8e18c7369f92c7a38a1d04513f60fb99502773aaa49accce044d99e00ab97c29e4d6fb339b8f9597dfee174d4a8e81c5b4b6ca4cadd47d2cb7945d68f

test:
  secret_key_base: d9958f14f513cb2fffcba3f58db082516ebd18dc5f8ee1ab5931e714344dc7f0cd207cc07653fa890f983884a6580b0517f26ba9ce0e576c8b025a6b4c6cadfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
